#!/usr/bin/env bash
#
# sync-help.sh — keep references/flags.md honest.
#
# The ADHD CLI gains and changes flags as the harness evolves, and a hand-copied flag list silently
# drifts out of date. To prevent that, flags.md carries a verbatim `adhd --help` block delimited by
# two HTML-comment markers. This script regenerates ONLY the text between those markers, leaving the
# curated cheat-sheet and prose above it untouched. Run it after upgrading `adhd`.
#
# Usage:  ./scripts/sync-help.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FLAGS_MD="$SCRIPT_DIR/../references/flags.md"

BEGIN="<!-- BEGIN adhd --help (auto-generated by scripts/sync-help.sh — do not edit by hand) -->"
END="<!-- END adhd --help -->"

if ! command -v adhd >/dev/null 2>&1; then
  echo "error: 'adhd' is not on your PATH. Link the harness first (run 'bun link' in the harness repo)." >&2
  exit 1
fi

if [ ! -f "$FLAGS_MD" ]; then
  echo "error: cannot find $FLAGS_MD" >&2
  exit 1
fi

HELP_FILE="$(mktemp)"
trap 'rm -f "$HELP_FILE"' EXIT
# Capture help on stdout only; discard shell-completion noise on stderr.
adhd --help >"$HELP_FILE" 2>/dev/null || true

if [ ! -s "$HELP_FILE" ]; then
  echo "error: 'adhd --help' produced no output." >&2
  exit 1
fi

if ! grep -qF "$BEGIN" "$FLAGS_MD" || ! grep -qF "$END" "$FLAGS_MD"; then
  echo "error: markers not found in $FLAGS_MD. Expected:" >&2
  echo "  $BEGIN" >&2
  echo "  $END" >&2
  exit 1
fi

OUT_FILE="$(mktemp)"
trap 'rm -f "$HELP_FILE" "$OUT_FILE"' EXIT

# Replace everything strictly between BEGIN and END with a fresh fenced help block.
awk -v begin="$BEGIN" -v end="$END" -v helpfile="$HELP_FILE" '
  $0 == begin {
    print
    print "```text"
    while ((getline line < helpfile) > 0) print line
    close(helpfile)
    print "```"
    skip = 1
    next
  }
  $0 == end { skip = 0; print; next }
  skip != 1 { print }
' "$FLAGS_MD" >"$OUT_FILE"

mv "$OUT_FILE" "$FLAGS_MD"
echo "Updated $(basename "$FLAGS_MD") from 'adhd --help'."
